SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS Domanda;
DROP TABLE IF EXISTS Tipologia;
DROP TABLE IF EXISTS Domanda_Risposta;
DROP TABLE IF EXISTS Risposta;


CREATE TABLE Domanda(
	ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	testo_domanda VARCHAR(255) NOT NULL,
	tipologia VARCHAR(255) NOT NULL,
	linkV VARCHAR(255) NOT NULL,
	linkF VARCHAR(255) NOT NULL,
	punteggio INT NOT NULL,
	tempo INT NOT NULL,
	ambito VARCHAR(255) NOT NULL,
	mobile BOOL DEFAULT FALSE,
	
	FOREIGN KEY(tipologia) REFERENCES Tipologia(tipologia)
							ON UPDATE CASCADE
	
)ENGINE=InnoDB;


CREATE TABLE Tipologia(
	tipologia VARCHAR(255) PRIMARY KEY NOT NULL
)ENGINE=InnoDB;


CREATE TABLE Domanda_Risposta(
	IDd INT NOT NULL,
	IDr INT NOT NULL,
	risposta_corretta BOOL DEFAULT FALSE,
	
	PRIMARY KEY (IDd, IDr),

	FOREIGN KEY(IDr) REFERENCES Risposta(ID)
						ON UPDATE CASCADE,
	FOREIGN KEY(IDd) REFERENCES	Domanda(ID)
						ON UPDATE CASCADE
						ON DELETE CASCADE

)ENGINE=InnoDB;

CREATE TABLE Risposta(
	ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	testo_risposta VARCHAR(255) NOT NULL	
)ENGINE=InnoDB;


SET FOREIGN_KEY_CHECKS=1;
